### ISSUE TITLE
genhostid always creates a new hostid

### ISSUE THREAD

**Issue by adilger** [fedora-sysv/initscripts#105]
When running `genhostid` it always stores a new value into `/etc/hostid`, even though `genhostid(1)` says this will happen *if `/etc/hostid` does not already exist.*

It looks like the bug is that it checks `st.st_size >= sizeof (n)` but on a 64-bit system this will always be false because this is declared as `long int n` and will be 8 bytes, but `/etc/hostid` is always a 32-bit value.  It should be enough to declare this as `int n` and then everything should work properly.

**Comment by deekej** [comment]
Thank you @adilger for the report, I can confirm this behaviour and indeed your observation is correct.

I will try to fix it when I get the chance.

**Comment by adilger** [comment]
@deekej - thanks for looking into this.  It also looks like `genhostid.1` should really be `genhostid.8`, since this is really a sysadmin command and not a regular user command.

What do you think about moving the `genhostid` command from `initscripts` over to `coreutils`, where the `hostid` command is already located?  Currently, `genhostid` is RHEL/Fedora/CentOS specific, but it would also be useful to have this on SLES and other distros as well.

**Comment by deekej** [comment]
So, I was discussing it with my colleagues on Friday and today...

Firstly, I'm OK to change the man page section for this utility, makes sense to me.
Secondly, I was already discussing the possibility to move it to `coreutils`, however, this will never be accepted by `coreutils` upstream since the `genhostid` manipulates a file in `/etc` folder. AFAIK, this is not covered by `coreutils` focus and therefore they will not accept it. The one alternative to move this would be `util-linux` package in Fedora.

Nevertheless, since we have `/etc/machine-id` which de-facto replace the `/etc/hostid` purpose, I'm thinking of dropping `genhostid` completely. The `/etc/machine-id` is unique identifier generated & used/maintained by `systemd`, and therefore I expect it to be adopted more widely in the future. Also, for system administrator it shouldn't be problem to move this `machine-id` file to new compute if needed (reinstall/migration) to keep the same `machine-id`.

So, here's what my proposed solution is:
=============================
1) Lets fix the `genhostid` utility.
2) Move the `genhostid` man page to *section 8*.
3) Add deprecation warning to `genhostid` utility, and remove it completely in Fedora 28 or 29.
