### ISSUE TITLE
sys-unconfig alternative needed for Fedora 30 

### ISSUE THREAD

**Issue by eran101** [fedora-sysv/initscripts#265]
I need to prepare a KVM template of Fedora 30 server.
The current version in the Fedora repository of initscripts is 10.02.
This version doesn't include sys-unconfig since it was removed in initscripts 9.81-1
[https://fedora.pkgs.org/30/fedora-x86_64/initscripts-10.01-2.fc30.x86_64.rpm.html](url)
What should I do?

**Comment by lnykryn** [comment]
http://libguestfs.org/virt-sysprep.1.html

**Comment by eran101** [comment]
Thanks.
I know this method but I get errors in Proxmox with a KVM virtual machine.
What other options are available?
I need to run it from the guest VM.

**Comment by eran101** [comment]
I found out it's a script and its contents:
```
#!/bin/sh

. /etc/init.d/functions

if [ $# -ne 0 ]; then
    echo $"Usage: sys-unconfig" >&2
    exit 1
fi

touch /.unconfigured
rm -f /etc/udev/rules.d/*-persistent-*.rules
poweroff
```

**Comment by lnykryn** [comment]
Yeah, that one is completely useless these days. It just creates the /.unconfigured, but I don't think that there is anything that reacts to it, on the next boot. And since we now have the persistent naming, it is no longer necessary to remove the udev rules. So this tool is no longer useful.

So I would just suggest using the virt-sysrep and report any issues that block you from using it.

**Comment by eran101** [comment]
> So I would just suggest using the virt-sysrep and report any issues that block you from using it.
I found out it can't work.
For now I'll probably have to install KVM on Linux separately to create the VM template:
[https://forum.proxmox.com/threads/virsh-list.51184/#post-237474](url)
