### ISSUE TITLE
How to install dnf on Fedora 28

### ISSUE THREAD

**Issue by djshah19** [fedora-sysv/initscripts#291]
By mistake, I removed libsolv and all its dependencies including dnf

Tried running this command 

yum-deprecated install dnf 

however getting Error: invalid version flag: if

pls help me fix this

**Comment by mathieu-aubin** [comment]
download the latest RPM packages of the stuff you have wrecked (hehe, i actually think im funny!) using wget/curl/whatever.

Then, using RPM instead of DNF (which is basically a wrapper), you can reinstall with `rpm -Uvh filename.rpm`

OR... better yet. Pay me all you own so that i donit for you and then tell the world how expensive of a dumbasss i am. Yes. The world is my oyster and i smell.

**Comment by lnykryn** [comment]
This is not related to initscripts at all. But as mentioned in the previous comment, you can install any package manually through rpm.
