### ISSUE TITLE
[ANNOUNCEMENT] - Split initscripts and network-scripts to different packages

### ISSUE THREAD

**Issue by jamacku** [fedora-sysv/initscripts#310]
We are planning to divide initscripts package into two packages for RHEL9+. Where network-scripts will be in there own package in EPEL (unsupported) and initscripts as such will remain supported.   

Reason being to encourage people to use NetworkManager instead of legacy network-scripts.

We are now in planning phase and we are looking for your opinions, so don't hesitate to reach to us.

**Comment by jamacku** [comment]
@davide125 could you please tell us your opinion from Facebook point of view?

**Comment by davide125** [comment]
Thanks for the heads up @jamacku. Splitting the repos shouldn't be an issue at all, and `network-scripts` is already its own separate package in RHEL 8. The move to EPEL isn't ideal for us, but in practice it won't be too much of a burden (especially now that we know it's coming and can plan for it).

Our plan for RHEL 9 is to re-evaluate internally `network-scripts` vs `NetworkManager` vs `systemd-networkd` and conduct some testing between now and then, so that we can make an informed decision on whether we want to stay on `network-scripts` or not in the future.
